apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: dspa
  namespace: physical-ai
spec:
  apiServer:
    deploy: true
    enableSamplePipeline: false
  database:
    mariaDB:
      deploy: true
      pvcSize: 10Gi
  objectStorage:
    minio:
      deploy: true
      # Using mirror due to quay.io/minio/minio rate limiting / unavailability
      image: quay.io/openshift-pipeline/minio-mirror:RELEASE.2025-09-07T16-13-09Z
      pvcSize: 20Gi
