apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  # Fix download jobs to work with OpenShift restricted SCC
  # by setting HOME=/tmp so pip can install packages to a writable location
  - path: download-job-home-env.yaml
    target:
      kind: Job
      name: download-.*